import pandas as pd
import joblib
from typing import Dict, Any, Tuple

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# 導入我們自己的模組
from .data_loader import load_data
from .feature_engineering import apply_feature_extraction, extract_features

# 定義常數
MODEL_PATH = "model.joblib"
FEATURE_COLUMNS = [
    'text_length', 'word_count', 'sentence_count', 'avg_word_length',
    'avg_sentence_length', 'punctuation_count', 'uppercase_count',
    'digit_count', 'punctuation_ratio', 'uppercase_ratio', 'digit_ratio'
]

def train_model() -> Dict[str, Any]:
    """
    執行完整的模型訓練與評估流程。
    
    Returns:
        Dict[str, Any]: 一個包含模型、標籤編碼器、測試集數據及預測結果的字典。
    """
    # 1. 載入資料
    print("正在載入資料...")
    raw_df = load_data()
    if raw_df.empty:
        print("資料載入失敗或資料為空，終止執行。")
        return None

    # 2. 特徵工程
    print("正在進行特徵工程...")
    featured_df = apply_feature_extraction(raw_df)
    
    X = featured_df[FEATURE_COLUMNS]
    y = featured_df['label']
    
    le = LabelEncoder()
    y_encoded = le.fit_transform(y)
    
    # 4. 分割資料集
    print("正在分割資料集...")
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
    )

    # 5. 訓練模型
    print("正在訓練模型...")
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # 6. 進行預測
    print("正在進行預測...")
    y_pred = model.predict(X_test)

    # 7. 評估模型
    print("\n模型評估結果：")
    accuracy = accuracy_score(y_test, y_pred)
    print(f"模型準確率 (Accuracy): {accuracy:.2f}")
    
    y_test_labels = le.inverse_transform(y_test)
    y_pred_labels = le.inverse_transform(y_pred)
    
    print("\n分類報告 (Classification Report):")
    print(classification_report(y_test_labels, y_pred_labels, zero_division=0))
    
    return {
        "model": model,
        "label_encoder": le,
        "X_test": X_test,
        "y_test": y_test_labels,
        "y_pred": y_pred_labels,
        "feature_columns": FEATURE_COLUMNS
    }

def save_model(training_results: Dict[str, Any], filepath: str = MODEL_PATH):
    """
    儲存訓練結果，包含模型、標籤編碼器及評估數據。

    Args:
        training_results (Dict[str, Any]): 從 train_model() 回傳的字典。
        filepath (str): 儲存路徑。
    """
    print(f"正在儲存模型及評估結果至 {filepath}...")
    joblib.dump(training_results, filepath)
    print("模型儲存成功。")

def load_model(filepath: str = MODEL_PATH) -> Dict[str, Any]:
    """
    載入儲存的模型及評估結果。

    Args:
        filepath (str): 模型檔案路徑。

    Returns:
        Dict[str, Any]: 包含模型、標籤編碼器及評估數據的字典，如果檔案不存在則回傳 None。
    """
    try:
        data = joblib.load(filepath)
        return data
    except FileNotFoundError:
        return None

def predict_text(text: str, model: RandomForestClassifier, le: LabelEncoder) -> Tuple[str, float]:
    """
    對單一文本進行預測。

    Args:
        text (str): 輸入文本。
        model (RandomForestClassifier): 訓練好的模型。
        le (LabelEncoder): 標籤編碼器。

    Returns:
        Tuple[str, float]: 預測的標籤和信賴度分數。
    """
    if not text:
        return None, 0.0

    # 提取特徵
    features = extract_features(text)
    features_df = pd.DataFrame([features], columns=FEATURE_COLUMNS)
    
    # 預測機率
    pred_proba = model.predict_proba(features_df)[0]
    
    # 找到最高機率的類別
    max_proba_idx = pred_proba.argmax()
    prediction = le.inverse_transform([max_proba_idx])[0]
    confidence = pred_proba[max_proba_idx]
    
    return prediction, confidence

if __name__ == '__main__':
    training_results = train_model()
    
    if training_results:
        # 儲存完整的訓練結果
        save_model(training_results)
        
        # 載入模型並測試
        loaded_data = load_model()
        if loaded_data:
            print("\n模型及評估資料載入成功，進行測試預測...")
            loaded_model = loaded_data["model"]
            loaded_le = loaded_data["label_encoder"]
            
            test_text_ai = "This is a test text generated by an artificial intelligence to see how the model reacts."
            test_text_human = "I went to the store this morning to buy some bread and milk for breakfast."
            
            pred_ai, conf_ai = predict_text(test_text_ai, loaded_model, loaded_le)
            print(f"測試文本 (AI): '{test_text_ai}'")
            print(f"  -> 預測: {pred_ai}, 信賴度: {conf_ai:.2f}\n")
            
            pred_human, conf_human = predict_text(test_text_human, loaded_model, loaded_le)
            print(f"測試文本 (Human): '{test_text_human}'")
            print(f"  -> 預測: {pred_human}, 信賴度: {conf_human:.2f}")
